name: Wrap

on:
  schedule:
    - cron: '2 2 * * *' #  UTC
  workflow_dispatch: {} # manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MY_ADDRESS: ${{ secrets.MY_ADDRESS }}
          WETH_CONTRACT_ADDRESS: ${{ secrets.WETH_CONTRACT_ADDRESS }}
          TAIKO_RPC_URL: ${{ secrets.TAIKO_RPC_URL }}
        run: python bot.py

      - name: Upload status file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: transaction-status
          path: transaction_status.json
          if-no-files-found: ignore
